module.exports.User = require("./user.model");
module.exports.Category = require("./category.model");
module.exports.Product = require("./product.model");
module.exports.Cart = require("./addcart.model");
module.exports.Order = require("./order.model");
module.exports.Payment = require("./payment.model");
module.exports.Shipper = require("./shipper.model");
// module.exports.Mobile= require("./mobileshop.model");
// module.exports.Book = require("./book.model");