module.exports.userService=require('./user.service');
module.exports.categoryService=require('./category.service');
module.exports.productService=require('./product.service');
module.exports.addcartService=require('./addcart.service');//validation pending
module.exports.orderService=require('./order.service');//validation pending
module.exports.paymentService=require('./payment.service');//validation pending
module.exports.shipperService=require('./shipper.service');
// module.exports.mobileService=require('./mobileshop.service');
// module.exports.bookService=require('./book.service');
